#!/bin/tcsh 

source /group/halld/Software/build_scripts/gluex_env_jlab.csh  /work/halld3/home/somov/lumi_skim/version_5.20.0.xml 

setenv HALLD_MY /work/halld3/home/somov/lumi_skim 

# setenv JANA_CALIB_URL mysql://ccdb_user@hallddb.jlab.org/ccdb

   
export CCDB_CONNECTION="mysql://ccdb_user@hallddb-farm.jlab.org/ccdb"

export JANA_CALIB_URL="mysql://ccdb_user@hallddb-farm.jlab.org/ccdb"

setenv JANA_CALIB_CONTEXT "variation=default"


# cd  /cache/halld/RunPeriod-2022-08/production/ver05_lumi/RUN_NUM

cd  /volatile/halld/home/somov_new/ver05_lumi/RUN_NUM

hd_root -PPLUGINS=lumi_skim -PLUMI_PRIMEX:DIR=TREE -PNTHREADS=4 -o /volatile/halld/home/somov_new/ver05_lumi/RUN_NUM/FILE.root /cache/halld/RunPeriod-2022-08/recon/ver01a/ps/EVIO  >& /work/halld3/home/somov_new/lumi_skim/lumi_primex3/individual/log/RUN_NUM/FILE.log


# hd_root -PPLUGINS=lumi_skim -PLUMI_PRIMEX:DIR=TREE -PNTHREADS=4 -o /cache/halld/RunPeriod-2022-08/production/ver05_lumi/RUN_NUM/FILE.root /cache/halld/RunPeriod-2022-08/recon/ver01/ps/EVIO  >& /work/halld3/home/somov/lumi_skim/lumi_primex3/individual/log/RUN_NUM/FILE.log
